# Generated by Django 3.1.3 on 2021-02-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateTimeField()),
                ('comprar', models.BooleanField(default=False)),
                ('pedido_enviado', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('reembolso_solicitado', models.BooleanField(default=False)),
                ('reembolso_aceptado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('aceptado', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=40)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio', models.PositiveIntegerField()),
                ('precio_rebajdo', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('stock', models.CharField(max_length=10)),
                ('productor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('T', 'Tintos'), ('B', 'Blancos'), ('E', 'Espumantes')], max_length=1)),
                ('variedad', models.CharField(choices=[('M', 'Malbec'), ('CS', 'Cavernet-Sauvignon'), ('B', 'Blend'), ('S', 'Sirah')], max_length=10)),
                ('corte', models.CharField(max_length=50)),
                ('alcohol', models.CharField(max_length=8)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carga_banda', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero_calle', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('tipo_direccion', models.CharField(choices=[('E', 'Envio'), ('F', 'Facturacion')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DireccionesFacturacion',
            },
        ),
        migrations.CreateModel(
            name='ComprarProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprar', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DireccionEnvio', to='Products.direccionfacturacion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DireccionFacturacion', to='Products.direccionfacturacion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.pago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(to='Products.ComprarProducto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
