# Generated by Django 3.1.3 on 2021-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
